config/routes.rb
TwitterAngellistBridge::Application.routes.draw do
  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", as: :signout

  root to: "pages#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
      user.twitter_oauth_token = auth["credentials"]["token"]
      user.twitter_oauth_token_secret = auth["credentials"]["secret"]
    end
  end

  def add_angellist_from_omniauth(auth)
    self.angellist_oauth_token = auth["credentials"]["token"]
    self.angellist_oauth_token_secret = auth["credentials"]["secret"]
    save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    if(auth["provider"] == "twitter")
      user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
      session[:user_id] = user.id
      redirect_to root_path, notice: "Signed in!"
    elsif(auth["provider"] == "angellist" && current_user)
      current_user.add_angellist_from_omniauth(auth)
      redirect_to root_path, notice: "Authenticated with Angellist!"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Signed out!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterAngellistBridge</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/index.html.haml
- if current_user
  - if current_user.angellist_oauth_token.present?
    You're authenticated with Angellist
  - else
    = link_to "Authenticate with Angellist", "/auth/angellist"

  = link_to "Signout", signout_path
- else
  = link_to "Sign in with Twitter", "/auth/twitter"